### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by ohnx** [mebsim/Timetable#1]
Hi, I am using Xcode Version 9.2 (9C40b) on macOS Sierra 10.12.6 (16G29).

I just opened this project in Xcode and when trying to build, I get this error:

```
/Users/mason/Downloads/Timetable-master/TimetableMenuBar/AppDelegate.swift:43:42: Cannot convert value of type 'String' to expected argument type 'NSImage.Name'
/Users/mason/Downloads/Timetable-master/TimetableMenuBar/TimetableViewController.swift:259:45: Cannot convert value of type 'String' to expected argument type 'NSStoryboard.Name'
```

**Comment by mebsim** [comment]
I'll look into it, it builds on mine (building mine in Xcode 10.0 on the newest version of macOS), but it might just be an error in how I uploaded

**Comment by mebsim** [comment]
Okay, I think I've narrowed down the issue. The two lines specified in the error were lines that were updated when changing to the newest version of Swift. They should build in a newer version of Xcode, but probably aren't supported in the older Xcode versions. They originally were:

`button.image = NSImage(named:NSImage.Name("StatusBarButtonImage"))` 
and 
`let storyboard = NSStoryboard(name: NSStoryboard.Name(rawValue: "Main"), bundle: nil)`

That should probably solve the issues in building it

**Comment by ohnx** [comment]
Ah, I see... Those two fixes, plus one more on line 263:

```
guard let viewcontroller = storyboard.instantiateController(withIdentifier: NSStoryboard.SceneIdentifier(rawValue: identifier)) as? TimetableViewController else {
```

let me build now :) must just be the different Swift/Xcode versions.

Looks good! I might submit some PR's with some suggested changes :)
